# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmreapp', '0024_historicalhystoryoffer_historicalhystoryservice_historicalhystoryshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u043a\u043e\u043c\u043c\u0438\u0441\u0438\u043e\u043d\u043d\u044b\u0445'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0434\u043e\u0433\u043e\u0432\u043e\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='contract_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0434\u043e\u0433\u043e\u0432\u043e\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='developmentid',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u041a\u043e\u0434 \u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0410\u0432\u0438\u0442\u043e'),
        ),
    ]
