# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmreapp', '0025_auto_20160408_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='apartments',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043a\u0432\u0430\u0440\u0442\u0438\u0440'),
        ),
        migrations.AddField(
            model_name='orderssale',
            name='developmentid',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u041a\u043e\u0434 \u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0410\u0432\u0438\u0442\u043e'),
        ),
    ]
