# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmreapp', '0026_auto_20160411_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionorganization',
            name='client',
            field=models.ForeignKey(default=263, on_delete=django.db.models.deletion.CASCADE, to='crmreapp.Clients', verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043a\u043b\u0438\u0435\u043d\u0442\u0430'),
            preserve_default=False,
        ),
    ]
