# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 20:51
from __future__ import unicode_literals

import crmreapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmreapp', '0027_constructionorganization_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430')),
                ('file', models.FileField(blank=True, null=True, upload_to=crmreapp.models.get_documents_path, verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': '\u041d\u043e\u0440\u043c\u0430\u0442\u0438\u0432\u043d\u044b\u0435 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b',
            },
        ),
    ]
