# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 11:04
from __future__ import unicode_literals

import crmreapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmreapp', '0028_regulations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulations',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=crmreapp.models.get_regulations_path, verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442'),
        ),
    ]
