# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmreapp', '0029_auto_20160612_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderssale',
            name='description',
            field=models.CharField(blank=True, max_length=6000, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0437\u0430\u044f\u0432\u043a\u0438'),
        ),
    ]
