# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmreapp', '0030_auto_20160619_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderssale',
            options={'ordering': ['create_date'], 'permissions': (('view_all_orders-sale', 'View all Orders Sale'), ('view_free_orders-sale', 'View free Orders Sale'), ('view_my_orders-sale', 'View my Orders Sale'), ('change_all_orders-sale', 'Change all Orders Sale'), ('share_orders-sale', 'Share Orders Sale'), ('lock_orders-sale', 'Lock Orders Sale'), ('uploading_orders-sale', 'Uploading Orders Sale'), ('uploading_orders-all', 'Uploading Orders All'), ('change_advertising', 'Change advertising')), 'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u043f\u0440\u043e\u0434\u0430\u0436\u0443'},
        ),
    ]
