# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-04 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmreapp', '0041_auto_20171105_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingphotos',
            name='description',
            field=models.CharField(max_length=60, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='orderssale',
            name='cadastre_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u041a\u0430\u0434\u0430\u0441\u0442\u0440\u043e\u0432\u044b\u0439 \u043d\u043e\u043c\u0435\u0440'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='description',
            field=models.CharField(max_length=60, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='planphotos',
            name='description',
            field=models.CharField(max_length=60, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
